### ISSUE TITLE
Broadcast IP calculation only works for /24 (255.255.255.0) subnet mask

### ISSUE THREAD

**Issue by briangeek** [mikedehaan/MusicFader#1]
This code in MusicFader.ino will only work for a /24:

    // Parse the localIP and change to the broadcast IP
    String ipAddressString;
    ipAddressString += WiFi.localIP().toString();

    // Parse 192.168.1.x and turn it into 192.168.1.255
    int ind1 = ipAddressString.indexOf('.');          //finds location of first .
    int ind2 = ipAddressString.indexOf('.', ind1+1 ); //finds location of second .
    int ind3 = ipAddressString.indexOf('.', ind2+1 );

    String broadcastString;
    broadcastString = ipAddressString.substring(0, ind3+1);
    broadcastString += "255";

Needs to be fixed to set the host bits to all 1's in IP address depending on subnet mask. e.g:
subnet mask 255.255.255.192
ip address 192.168.1.20
broadcast should be calculated as: 192.168.1.63

**Comment by mikedehaan** [comment]
Awesome! Thank you for pointing this out! You rock!

Should be fixed via this Pull Request: https://github.com/mikedehaan/MusicFader/pull/2
